### ISSUE TITLE
(Question) How does System address makes a call to smart contract without having positive balance?

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/parity-ethereum#1]
In PoA networks, there is SYSTEM_ADDRESS
`0xfffffffffffffffffffffffffffffffffffffffe`
that makes a call to `finalizeChange`
https://github.com/poanetwork/poa-network-consensus-contracts/blob/master/contracts/PoaNetworkConsensus.sol#L95

Usually, in Ethereum world, in order to make tx, you have to have some balance on your account.
How does SYSTEM_ADDRESS violates this rule?

**Comment by DemiMarie** [comment]
This is not an issue any more.

**Comment by afck** [comment]
To clarify: Our understanding is that the system address can't actually make _transactions_.

* Regular transactions have to be signed and paid for by the sender.
* There are mechanisms to whitelist certain _service transactions_. Those have zero gas price, but still have to be _signed_ by the sender.
* Finally, contract calls can be made _implicitly_ by the system address, outside a transaction. Those don't log events, and they can only have parameters that are known in advance by _all nodes_ (not only the block author, and not even only the validators). No information about them is put into the block at all. They are just executed implicitly by every node that handles the block.
