### ISSUE TITLE
Replace `tokio_core` with `tokio` in the `util/fetch` crate

### ISSUE THREAD

**Issue by c0gent** [poanetwork/parity-ethereum#10]
As part of an ongoing effort to replace `tokio_core` with `tokio` throughout the Parity ecosystem, the [`fetch`](https://github.com/poanetwork/parity-ethereum/tree/master/util/fetch) crate needs to be updated and crate-specific tests must pass.

This will also require updating `hyper` to 0.12 and `hyper-rustls` to 0.14.

**Comment by fhaynes** [comment]
@c0gent I started on this over here: https://github.com/fhaynes/parity-ethereum/tree/10-replace-tokio_core-fetch. It is still very much a WIP, but it compiles at least with hyper 0.12 and hyper-rustls to 0.14 now. Admittedly, this required several blood sacrifices to Leviathan...

I'll pick this up again on the weekend and see if I can finish it up.

**Comment by fhaynes** [comment]
Also, do you want me to make a WIP PR so we can all review it? This project looks a bit busier, so I don't want to disrupt any workflows.

**Comment by c0gent** [comment]
Sure. And feel free to ask any questions if there are things you can't figure out. I can't promise immediate responses but I'll do my best.

**Comment by fhaynes** [comment]
Thanks, I appreciate it! =) The main issue is the large number of changes in hyper 0.12. There are lots of little things that need to be updated across the entire crate.
