### ISSUE TITLE
Make malice reports testable in integration tests.

### ISSUE THREAD

**Issue by afck** [poanetwork/parity-ethereum#101]
To test in an actual network (with multiple Parity instances) whether #97 works correctly, let's add a configuration option to simulate malice and/or malice reports—in a separate, temporary branch that will never get merged or released, of course!

We should simply add an option that will make the node call `report_malicious` at a specified block number.

If feasible, we could also make a node misbehave and produce an invalid block (step less or equal than parent's step) that should trigger [this line](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/engines/authority_round/mod.rs#L1323) in all the other nodes.

**Comment by afck** [comment]
I implemented the first part in the [`afck-sim-malice` branch](https://github.com/poanetwork/parity-ethereum/tree/afck-sim-malice). I tried it with the current [`posdao-test-setup`](https://github.com/poanetwork/posdao-test-setup) and the following addition to the chain spec (under `engine` → `authorityRound` → `params`):
```json
"reportMalicious": {
  "5": "0xbbcaa8d48289bb1ffcf9808d9aa4b1d215054c78"
}
```
It successfully reported and removed the validator `0xbbca…`. The report transactions were committed in block 6 and the event emitted in block 7:
```
InitiateChange:
[ '0x522df396Ae70a058BD69778408630FdB023389B2',
  '0x75df42383afE6Bf5194AA8fA0e9b3D5F9e869441' ]
```

**Comment by varasev** [comment]
Ok, now we see that `report_malicious` works fine :+1:  How complicated would it be to make a node misbehave and produce an invalid block?

**Comment by afck** [comment]
I updated the [`afck-sim-malice` branch](https://github.com/poanetwork/parity-ethereum/tree/afck-sim-malice) to allow scheduling the production of faulty blocks:
```json
"faultyBlocksTransition": {                                                                                                                                                                                                                                         
  "0x75df42383afE6Bf5194AA8fA0e9b3D5F9e869441": "15"                                                                                                                                                                                                                
}
```
With that, node `0x75df…` starts putting the wrong step number into its block headers starting at block 15—or 16, in practice, because block 15 is another node's turn.
The test was successful and `0x75df…` got itself banned. As expected, a correct block 16 was produced by `0x522d…` instead, and block 17 contained the event:
```
InitiateChange:
[ '0xbbcaA8d48289bB1ffcf9808D9AA4b1d215054C78',
  '0x522df396Ae70a058BD69778408630FdB023389B2' ]
```

(I also tried making node 1, `0xbbca…`, the faulty one. That worked, too, but it confused the `watcher` script, which simultaneously output the faulty block and a valid block.)

**Comment by varasev** [comment]
@afck Could you repeat your test https://github.com/poanetwork/parity-ethereum/issues/101#issuecomment-465596398 ? It doesn't work for me: I don't see emitting of the `InitiateChange` event.

**Comment by afck** [comment]
You're right; I still see
```
Reporting 0xbbca…4c78 as malicious FOR TESTING PURPOSES.
```
but the validator doesn't seem to get removed. Not sure yet why that broke again.

**Comment by varasev** [comment]
I'll investigate this with the `posdao-test-setup` too.

**Comment by phahulin** [comment]
Done in `afck-sim-malice`
