### ISSUE TITLE
AuRa skips receiving InitiateChange even if it was emitted

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/parity-ethereum#112]
This line prevents AuRa from receiving `InitiateChange` even if `emitInitiateChange` was called in the same step if the current step is not the first step of an epoch: https://github.com/poanetwork/parity-ethereum/blob/b5097c67155debd9aee2c5e499456b4a1f187b26/ethcore/src/engines/authority_round/mod.rs#L1151

This affects handling malicious validator reports. The pending validator set change scheduled by `reportMalicious` cannot be implemented until the start of the next epoch.

**Comment by varasev** [comment]
Note that Parity ignores several `InitiateChange` events before the `ValidatorSet.finalizeChange` function is called. When we emit the `InitiateChange`, we must wait for the validator set is applied by the engine. We only can emit some next `InitiateChange` after the previous is applied (the `ValidatorSet.finalizeChange` is called).

**Comment by varasev** [comment]
Is it still actual? What steps should we perform to catch that?

**Comment by vkomenda** [comment]
It was related to failing test that have been fixed since then.
