### ISSUE TITLE
Map the transaction flow.

### ISSUE THREAD

**Issue by afck** [poanetwork/parity-ethereum#12]
For hbbft integration (#8), we'll probably need to make a few deeper changes to how transactions are assembled into blocks. To get a better understanding of the system and of what we'll need to change, let's map the flow of a transaction from the point where it is received from the user, to the point where its block is fully sealed and verified.

As discussed, let's start from the point where the transaction is put into a block ([here?](https://github.com/paritytech/parity-ethereum/blob/5a1dc3eb8a638d556248799d6a1f60e528331f40/ethcore/src/miner/miner.rs#L466)); I'll follow the transaction backwards, and @DrPeterVanNostrand will follow the block forwards.

**Comment by c0gent** [comment]
Well done @DrPeterVanNostrand.
