### ISSUE TITLE
Changing the value of `stepDuration` option in `spec.json` for AuRa

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#122]
Please figure out how we could create an option `stepDurationTransition` for Parity client which would allow us to change block time for an existing PoA chain at the specified future block (simultaneously for all validators). This is for changing the value of `stepDuration` param in `spec.json`. For example: https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L6

**Comment by vkomenda** [comment]
Adding this to aura-pos project for now. Every engine with a step duration parameter will have to define the `stepDurationTransition` option on its own if it is needed. As such, the option is an attribute of a particular engine.

**Comment by varasev** [comment]
It's better if we make something like [`multi`](https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L11) option for this which would allow switching the value of `stepDuration` several times:

```
"stepDuration": {
  "0": 5,
  "1000": 7,
  "123123": 10
}
```

**Comment by vkomenda** [comment]
This is possible. Does `multi` always contain validator sets with a step duration parameter? If not, we could still add `stepDurationTransition` to those entries of `multi` which do contain `stepDuration`.

One remark is that `stepDuration` already appears at the upper level in the JSON struct. If we add the transitions to `multi`, we could either remove `stepDuration` from the top level (however that would make using `multi` a requirement), or disallow an extra entry at block 0, or add a new entry type, say `stepDurationTransition` with the value being the duration.

I prefer the latter option. I'm not sure about how to combine it with a contract change in the same block. That might not work. Maybe we need to bundle the step duration with a contract address in the same entry of `multi`?

**Comment by varasev** [comment]
No, `stepDuration` changing shouldn't be related to the [`multi` option for the validator set changing](https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L11-L24).

I mentioned the [`multi` option for validator set](https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L11-L24) just to show that `stepDuration` switching could work the same way.

I would expect that we would have `"stepDuration": {"0": 5}"` instead of `"stepDuration": 5` at [line 6 of the `spec.json`](https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L6).

That would mean that initial `stepDuration` is 5 seconds (taking effect from the genesis block).

When we need to change it to 7 seconds, we will complement it by block number on which we'd like to set the new duration. Example:

```
{
  "name": "Sokol",
  "engine": {
    "authorityRound": {
      "params": {
        "stepDuration": {
          "0": 5,
          "100": 7
        },
        "blockReward": "0xDE0B6B3A7640000",
        "maximumUncleCountTransition": 0,
        "maximumUncleCount": 0,
        ...
```

The example above means that `stepDuration` from the block `0` to the block `99` is 5 seconds, and it's value is 7 seconds for other blocks beginning from the block number `100`.

The [`multi` for validator set](https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L11-L24) works the same way: the address of ValidatorSet contract was [`0x8bf38d4764929064f2d4d3a56520a76ab3df415b`](https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L13). This contract was used from genesis block to the block number `362295`. Beginning from the block `362296` there was used another ValidatorSet contract with address [`0xf5cE3f5D0366D6ec551C74CCb1F67e91c56F2e34`](https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L16). At the moment the ValidatorSet deployed on the address `0x4c6a159659CCcb033F4b2e2Be0C16ACC62b89DDB` is used: https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L22

If we decide to deploy a new validator set contract for some reason, we will append a future block address and a new ValidatorSet contract address to the list of the [`multi` switches](https://github.com/poanetwork/poa-chain-spec/blob/e36f2147948b1e84541f96d37ad154725d64348c/spec.json#L11-L23).

It would be great to see the same for the `stepDuration` parameter.

**Comment by vkomenda** [comment]
@varasev, I see your point now. If we make `stepDuration` to be a list of pairs then we need to ensure that it's non-empty, or set a default block duration if it's empty.

A way to ensure non-emptiness would be something like
```
"stepDuration": {
  "initial": 5,
  "subsequent": {
    "99": 7,
    "199": 9
  }
}
```
where `initial` is a mandatory field and `subsequent` is an optional field which may contain an empty list of pairs. To avoid redefining the duration for step 0 we could interpret block numbers as the last block numbers of the previous step duration. So, in the example above blocks 0..99 have duration 5, blocks 100..199 have duration 7, and blocks 200.. have duration 9.

**Comment by varasev** [comment]
> If we make stepDuration to be a list of pairs then we need to ensure that it's non-empty, or set a default block duration if it's empty.

Of course, we should ensure that the `stepDuration` is non-empty.

For your scheme, it's a bit confusing that "99" included in blocks band (0...99). As a user who worked with the `multi` for validator set I would expect `"99": 7` means that 7-seconds blocks begin from the block 99 (not from the block 100). So, let's just implement the next scheme (which is more familiar for those who saw the `multi` option):

```
"stepDuration": {
  "0": 5,
  "1000": 7,
  "2000": 10
}
```

This example means that blocks 0...999 are 5-seconds, blocks 1000...1999 are 7-seconds, and blocks >= 2000 are 10-seconds.

By default

"stepDuration": {
  "0": 5
}

must always be defined. It should mean the same as `"stepDuration": 5` (for backward compatibility).

This is like non-multi `list` option for validator set: https://wiki.parity.io/Validator-Set.html#immutable-list Example:

```
"validators": {
    "list": [
        "0x7d577a597b2742b498cb5cf0c26cdcd726d39e6e",
        "0x82a978b3f5962a5b0957d9ee9eef472ee55b42f1"
    ]
}
```

It is the same as

```
"validators": {
    "multi": {
        "0": {
            "list": [
                "0x7d577a597b2742b498cb5cf0c26cdcd726d39e6e",
                "0x82a978b3f5962a5b0957d9ee9eef472ee55b42f1"
            ]
        }
    }
}
```

I made an experiment for the `list` option which shows that switching `validators.list` to `validators.multi.0.list` works fine in Parity. The same I would expect for the `stepDuration` option:

Initially, it can be set to `stepDuration: 5` but if we change it to

"stepDuration": {
  "0": 5
}

and restart the node, nothing wrong should occur.

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/parity-ethereum/pull/152.
