### ISSUE TITLE
POSDAO reportMalicious implementation

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#136]
For POSDAO we need to change the way the [`reportMalicious` function](https://wiki.parity.io/Validator-Set.html#reporting-contract) is called in AuRa upstream implementation.

We have already discussed it in https://github.com/poanetwork/parity-ethereum/issues/97 and https://github.com/poanetwork/parity-ethereum/pull/98, but didn't yet implement. The related PRs and issues: #129, #107, #101, #98, #97, #93. There are so many discussions in those PRs that I decided to describe what we need from scratch here.

## How it works at the moment

In the upstream Parity implementation, the `reportMalicious` function is called by every validator on the next block after they discover that some validator misbehaved.

For example, we have 5 validators and one of them is malice:

validator1 - honest
validator2 - honest
validator3 - honest
validator4 - honest
validator5 - malice

When the `validator5` misbehaves at block number `100`, other validators (validator1...validator4) perform a `reportMalicious` transaction at block number `101`.

For the described demo case, the validators call the [`reportMalicious`](https://github.com/poanetwork/posdao-contracts/blob/240c1a3c3701ca094a0337006f39d663b63424f2/contracts/ValidatorSetAuRa.sol#L66) as follows:

validator1 calls `reportMalicious(validator5, 100, [])` at block 101
validator2 calls `reportMalicious(validator5, 100, [])` at block 101
validator3 calls `reportMalicious(validator5, 100, [])` at block 101
validator4 calls `reportMalicious(validator5, 100, [])` at block 101

The misbehaviour checking occurs in the [`verify_block_family` function in mod.rs](https://github.com/paritytech/parity-ethereum/blob/412e2ce3a067244ac2bcd9dc23288cc2347872bb/ethcore/src/engines/authority_round/mod.rs#L1265-L1271). We see that the `verify_block_family` function invokes the [`report_malicious` function from the `contract.rs`](https://github.com/paritytech/parity-ethereum/blob/412e2ce3a067244ac2bcd9dc23288cc2347872bb/ethcore/src/engines/validator_set/contract.rs#L112-L118). The `report_malicious` function makes a regular transaction to call the [`ValidatorSet.reportMalicious`](https://github.com/poanetwork/posdao-contracts/blob/240c1a3c3701ca094a0337006f39d663b63424f2/contracts/ValidatorSetAuRa.sol#L66) function. The transaction is formed by the [`transact` function](https://github.com/paritytech/parity-ethereum/blob/412e2ce3a067244ac2bcd9dc23288cc2347872bb/ethcore/src/engines/validator_set/contract.rs#L54) which invokes the [`Client.transact_contract` func](https://github.com/paritytech/parity-ethereum/blob/412e2ce3a067244ac2bcd9dc23288cc2347872bb/ethcore/src/client/client.rs#L2157-L2181).

## What's the problem

There're several problems with the upstream implementation:

`1)` The transaction is called by validator's mining address. The address has a nonce which is incremented periodically when [`RandomAuRa`](https://github.com/poanetwork/posdao-contracts/blob/240c1a3c3701ca094a0337006f39d663b63424f2/contracts/RandomAuRa.sol) functions are called by the same mining address due to [POSDAO White Paper](https://forum.poa.network/t/posdao-white-paper/2208) conditions.

If the `reportMalicious` transaction is called in the same block when `RandomAuRa`'s function is called, the `reportMalicious` transaction fails because it has the same nonce as the `RandomAuRa` transaction.

Or if the `reportMalicious` transaction is called twice for two different malice validators in the same block, there is also the same `nonce issue`. For example, we have 5 validators and two of them are malice on the same block number `100`:

validator1 - honest
validator2 - honest
validator3 - honest
validator4 - malice
validator5 - malice

`2)` The transaction is called with a non-zero gas price. Since the mining address in most cases will have zero balance, we need the transaction to be performed with zero gas price.

~`3)` The transaction is called with [inaccurate gas limit](https://github.com/paritytech/parity-ethereum/blob/412e2ce3a067244ac2bcd9dc23288cc2347872bb/ethcore/src/client/client.rs#L2171) which can be wrong, because the `reportMalicious` function [works with arrays](https://github.com/poanetwork/posdao-contracts/blob/240c1a3c3701ca094a0337006f39d663b63424f2/contracts/ValidatorSetAuRa.sol#L89-L93). AFAIK, the gas limit definition for such functions works wrong in most cases. This can easily be solved by multiplying the [`gas` parameter here](https://github.com/paritytech/parity-ethereum/blob/412e2ce3a067244ac2bcd9dc23288cc2347872bb/ethcore/src/client/client.rs#L2171) by `1.5` to increase it by 50% (making an extra margin this way).~

## How it should work

The idea outlined in https://github.com/poanetwork/parity-ethereum/issues/97 and https://github.com/poanetwork/parity-ethereum/pull/98 is to make a queue of tuples `(address _maliciousMiningAddress, uint256 _blockNumber)` in a node's memory.

When a [misbehaviour occurs](https://github.com/paritytech/parity-ethereum/blob/412e2ce3a067244ac2bcd9dc23288cc2347872bb/ethcore/src/engines/authority_round/mod.rs#L1265-L1266) we need to add the `header.author()` and `header.number()` to the queue of tuples instead of [calling the `reportMalicious` immediately](https://github.com/paritytech/parity-ethereum/blob/412e2ce3a067244ac2bcd9dc23288cc2347872bb/ethcore/src/engines/authority_round/mod.rs#L1269).

So, each item in the queue would have `(address _maliciousMiningAddress, uint256 _blockNumber)` tuple.

Every two blocks a node should do the following steps:

Set some local nonce counter to the current nonce of the node's mining address. For example, let's name this variable `nonceCounter`.

`1.` Get a number of the current block from the blockchain. Let's name it `currentBlock`.

`2.` Go through all the items in the queue. For each item:

`2.1.` Compare the `currentBlock` with the `_blockNumber` from tuple: if `currentBlock - _blockNumber > 100` then remove the tuple from the queue. Otherwise, go to step 2.2:

`2.2.` Call the `ValidatorSet.isValidatorBanned(address _miningAddress)` getter: if it returns `true`, remove the tuple from the queue. Otherwise, go to step 2.3:

`2.3.` Call the `ValidatorSet.maliceReportedForBlock(address _maliciousMiningAddress, uint256 _blockNumber)` getter: it returns an array of reporters for this tuple. If the current node's mining address is in the array, remove the tuple from the queue. Otherwise, go to step 2.4:

`2.4.` Send `reportMalicious` transaction: pass into the `reportMalicious` function the parameters from the tuple: [`reportMalicious(_maliciousMiningAddress, _blockNumber, [])`](https://github.com/poanetwork/posdao-contracts/blob/240c1a3c3701ca094a0337006f39d663b63424f2/contracts/ValidatorSetAuRa.sol#L66) (the last parameter is an empty array of bytes: `Default::default()` in Parity, I guess).

The corresponding transaction must have:
- a zero gas price
- ~a gas limit increased by 50% relative to calculated by [`self.importer.miner.sensible_gas_limit()`](https://github.com/paritytech/parity-ethereum/blob/412e2ce3a067244ac2bcd9dc23288cc2347872bb/ethcore/src/client/client.rs#L2171)~
- the nonce taken from the `nonceCounter` local variable

Increment the `nonceCounter` and go to the next queue item.

## How to test this

We will test this manually with `posdao-test-setup` repo. For that, we will need the same spec parameters described [here](https://github.com/poanetwork/parity-ethereum/issues/101#issuecomment-465596398) and [here](https://github.com/poanetwork/parity-ethereum/issues/101#issuecomment-465949153). They are implemented in the commit https://github.com/poanetwork/parity-ethereum/commit/05205077d5ec5563f4cf6348437d91e2cc8ea315.

## Stuff

All the described things should have been implemented in https://github.com/poanetwork/parity-ethereum/pull/129 (but it doesn't work) so part of the code from that PR could be used.

**Comment by vkomenda** [comment]
> Every two blocks a node should do the following steps

Why do you think every other block should be skipped?

**Comment by varasev** [comment]
> Why do you think every other block should be skipped?

There should be some small time gap between checkings because doing this on every block is too often (the transaction should have time to be mined).

**Comment by vkomenda** [comment]
> When a misbehaviour occurs we need to add the header.author() and header.number() to the queue of tuples instead of calling the reportMalicious immediately.

We now decided to keep those immediate calls to `reportMalicious` and have additional resending of those reports if `maliceReportedForBlock` requires that. See #138.

**Comment by varasev** [comment]
Done in #129.
