### ISSUE TITLE
Add `posdaoTransition` option into `engine.authorityRound.params` of `spec.json`

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#141]
In order to be able to migrate an existing xDai network to POSDAO model, we will first need all the xDai validators to change their Parity clients to our modified version (from the `aura-pos` branch).

The `aura-pos` version must be able to work with the base AuRa network (such as xDai or POA Core) which doesn't contain things like `Random` contract, modified `reportMalicious`, and `emitInitiateChange` function. For that reason, we need to have a `posdaoTransition` spec option in the `engine.authorityRound.params` section of `spec.json` and make those things work only if the current block is greater or equal to defined in the `posdaoTransition`.

So, the `aura-pos` version must work exactly the same way as the `upstream stable` works before the block defined in the `posdaoTransition` option is applied.

Thus, `posdaoTransition` spec option is just a block number at which our Parity client modifications (listed in section 9.3 of the WhitePaper, excluding the `quorum23Transition` option which we already have) must begin to work. We need it to have backward-compatible Parity client which would work with the current xDai network before switching to POSDAO model.

**Comment by vkomenda** [comment]
We could keep the `aura-pos` engine alongside the original AuRa in our fork. xDai validators would first update their client to the version which has both engines implemented. Then the validators would start that client with the option `posdaoTransition` and switch from AuRa to AuRa-PoS at a given point.

**Comment by afck** [comment]
I don't think our changes so big that it makes sense to keep two separate engines; we just need to make everything backward compatible, and only activate the changed behavior after the transition block.

**Comment by varasev** [comment]
> I don't think our changes so big that it makes sense to keep two separate engines; we just need to make everything backward compatible, and only activate the changed behavior after the transition block.

Yes, that's what I meant.

**Comment by vkomenda** [comment]
> I don't think our changes so big that it makes sense to keep two separate engines; we just need to make everything backward compatible, and only activate the changed behavior after the transition block.

Yet as soon as the validators update their clients they will be running the AuRa-PoS engine, not AuRa. I'm sure our changes are not very deep but technically the engine is different and behaves differently.

**Comment by varasev** [comment]
The main thing is that a non-posdao AuRa network must continue working without any errors when the validators change their Parity nodes to the `aura-pos` version (as the first step of xDai migration to POSDAO model). The second migration step will be to update their `spec.json`s to switch the contracts to POSDAO, but this step can be much later after the first one (a week or two) because the validators will update their nodes to `aura-pos` carefully one by one to make sure nothing is broken.

**Comment by afck** [comment]
> technically the engine is different

The engine implementation contains many "transitions" that make it technically different, but that allow backward compatible functionality. I don't think our changes are much different from or deeper than e.g. the "empty steps transition". It still shares probably 95% of the code with the upstream Aura.

**Comment by vkomenda** [comment]
Will `posdao_transition` be expected to be always less than other POSDAO transitions such as `quorum_2_3_transition` and `block_reward_contract_transitions`? If so then the gating of POSDAO features until `posdao_transition` is easier than if those other transitions were allowed to come first.

**Comment by varasev** [comment]
The `posdaoTransition` shouldn't depend on `blockRewardContractTransition` and `quorum23Transition` (since these transitions are not posdao-specific). All these options can have arbitrary block numbers.

That's what the `posdaoTransition` option should enable:
- randomness feature (generating random number and calling the `Random` contract functions);
- `emitInitiateChange` feature;
- modified `reportMalicious` feature.

**Comment by varasev** [comment]
Also, the `posdaoTransition` should be off by default like the `quorum23Transition`.

I.e. if there is no `posdaoTransition` in spec, that means it is switched off.

**Comment by vkomenda** [comment]
> Also, the posdaoTransition should be off by default like the quorum23Transition.

More precisely, `quorum_2_3_transition` is set to `BlockNumber::max_value` if it is not provided in the config.

But I can keep `posdao_transition` as `None` if it is missing from the config.

**Comment by varasev** [comment]
Let's keep it as `None`.
