### ISSUE TITLE
Update aura-pos to include paritytech#10669

### ISSUE THREAD

**Issue by lazaridiscom** [poanetwork/parity-ethereum#143]
blocks https://github.com/paritytech/parity-ethereum/issues/10708)

update the poanetwork parity client to

* latest parity master, or at least
* to the version which contains the reset-functionality (https://github.com/paritytech/parity-ethereum/pull/10669/files#diff-40c7c65265e511d07158f62712f69573R1327)

## minimal

* Apply #10669 to the aura-pos branch ( 10699 corrects the already included #9782 )

**Comment by varasev** [comment]
We have updated the `aura-pos` to upstream's stable v2.4.5. Does `v2.4.5` contain the `reset` function?

**Comment by lazaridiscom** [comment]
@varasev , Yes, the initial reset (https://github.com/paritytech/parity-ethereum/pull/9782) in within v2.4.5.

But this was corrected 3 weeks ago within https://github.com/paritytech/parity-ethereum/pull/10669, which is not in v2.4.5 and in your aura_pos branch.

So this would be needed (i've not tried, possibly this can be merged easily).

**Comment by varasev** [comment]
@afck @vkomenda Could we rebase the `aura-pos` branch on the `v2.4.6 stable`?

**Comment by varasev** [comment]
Sorry, it seems that https://github.com/paritytech/parity-ethereum/pull/10669 is not in the upstream's stable branch yet.

> So this would be needed (i've not tried, possibly this can be merged easily).

@lazaridiscom Could you try to include that PR into the `aura-pos` but in the different branch? (say, `aura-pos-with-pr10669`)

**Comment by lazaridiscom** [comment]
I can try on my work-fork.

(Still, possibly take a look to move over to 2.4.6 (possibly there merging is easier). Going master would be the ideal, though.)

**Comment by varasev** [comment]
> Going master would be the ideal, though.

Usually, we only rebase the `aura-pos` on the `stable` upstream branch, so if you need to check that rebased on upstream `master`, you can try to do that in a separate branch.

**Comment by lazaridiscom** [comment]
When do you expect to have aura-pos on  2.4.6 available?

**Comment by varasev** [comment]
> When do you expect to have aura-pos on 2.4.6 available?

Not sure about the timing, but I asked our Rust developers above to do that. I guess, one of them will answer as soon as he will ready.

**Comment by lazaridiscom** [comment]
It has finally just 2 minor merge-conflicts, so all fine for now.

**Comment by lazaridiscom** [comment]
@varasev , I'm closing this for now, as i understand that you keep your `aura-pos` branches identical to the stables. Will reopen if needed.

**Comment by varasev** [comment]
> as i understand that you keep your aura-pos branches identical to the stables

The `aura-pos` branch contains our modifications needed for POSDAO model we are working on (see our [WhitePaper](https://sjc1.discourse-cdn.com/business5/uploads/poa1/original/2X/7/7c179aef2b57f12f3dbaa4198a8621b3d2e47bb3.pdf), section `9.3` if interested). But we also keep the `aura-pos` branch up-to-date with the upstream's stable branch.
