### ISSUE TITLE
Make posdao customizations compile-time applyable to original parity client

### ISSUE THREAD

**Issue by lazaridiscom** [poanetwork/parity-ethereum#146]
## Problem

Currently, the posdao version needs to be rebased manually against the latest stable versions.

## Enhancement

Provide solutions in order to be able to use the original parity-client, and add the customizations at compile-time.

(Ideally, customization would be loaded at runtime)

**Comment by vkomenda** [comment]
> Provide solutions in order to be able to use the original parity-client, and add the customizations at compile-time.

Are you asking to upstream features implemented in `aura-pos`? Not sure what compile-time customisations you have in mind. Could you please elaborate on your needs.

> (Ideally, customization would be loaded at runtime)

Do you mean application by dynamic linking or as a separate binary communicating with the original Parity client? It's possibly not related to the current goals of POSDAO and would still require instrumentation in the Parity-Ethereum client to allow such linking or communication to take place.

**Comment by lazaridiscom** [comment]
@vkomenda , I possibly expressed myself not clear.

 it's just about making your life easier, e.g. not having to worry about merging/rebasing the stable parity version. So you always have an up-to-date custom version.

In the ideal world, the parity-client would allow for loadable consensus-plugins, e.g. `--consensus=posdao`, which would load the plugin to the client at runtime.

Something similar (and easier) could be done for compile-time: e.g. 

```
fetch parity
fetch your consensus
=> build custom client
```

Things should be quite easy, if paritytech wants such functionality in its client. If not, it should be still doable, with some more effort.

**Comment by vkomenda** [comment]
It's not as easy as it sounds.

**Comment by lazaridiscom** [comment]
I know, but its a worthful goal.

**Comment by vkomenda** [comment]
Would you be happy if the `aura-pos` changes are merged upstream instead of starting to develop a plugin infrastructure within Parity-Ethereum?

**Comment by lazaridiscom** [comment]
Yes, would make things easy, too (and with lesser effort I guess...)
