### ISSUE TITLE
Aura doesn't report multiple blocks in one step.

### ISSUE THREAD

**Issue by afck** [poanetwork/parity-ethereum#164]
If a validator produces two sibling blocks in the same steps, that should be considered malicious behavior, but it is not detected by the current implementation. We should port equivocation detection from [the Aura implementation in Substrate](https://github.com/paritytech/substrate/blob/65b5c845c6ebb55cc09091d80e377f7630771347/core/consensus/slots/src/aux_schema.rs#L75). (See Gitter: [1](https://gitter.im/paritytech/parity?at=5d1b7af82e3f4317635bc776), [2](https://gitter.im/paritytech/parity?at=5d1b7cf06658420b1cde737d))

**Comment by vkomenda** [comment]
I'm thinking to maintain a summary map of blocks received from peers in AuRa. The map would have steps as keys and sets of pairs of the block author and the block header hash. Records older than a given number _N_ of steps would be periodically deleted.

This would compensate for the absence of a backend header database functionality present in Substrate.

Does this sound plausible?

**Comment by afck** [comment]
That sounds good.
But doesn't Parity's database contain all that's needed, too? (It might make sense to add that map to Aura anyway, of course, if it's cumbersome to access it otherwise.)

**Comment by vkomenda** [comment]
> But doesn't Parity's database contain all that's needed, too?

Possibly. However I still don't see it. AuRa has `RollingFinality::headers` which can be used but it only contains unfinalised headers. We probably need to compare against finalised headers as well. However that is probably taken care of. I think `verify_block_family` shouldn't be called for steps with finalised blocks.

> It might make sense to add that map to Aura anyway, of course, if it's cumbersome to access it otherwise.

I'll think about reusing `RollingFinality::headers` since I still have some doubts. Maybe I add that new map to AuRa.

**Comment by afck** [comment]
I was thinking of `Client`'s [`chain` field](https://github.com/poanetwork/parity-ethereum/blob/1c62c33dae03035cf6e80f117c4a71867f739ce1/ethcore/src/client/client.rs#L189); I think that has the methods needed to retrieve blocks and headers? (Or maybe a method to get a header by block number needs to be added.)

**Comment by vkomenda** [comment]
How about we use `Client::chain::block_headers` for finalised blocks and `RollingFinality::headers` for non-finalised?

**Comment by afck** [comment]
I'd expect you shouldn't need `RollingFinality::headers` at all… but whatever works best. :+1:

**Comment by vkomenda** [comment]
If we only compare against finalised blocks, we should miss non-finalised siblings, I think.

**Comment by afck** [comment]
Sure, only using finalized blocks is useless, because if there's an equivocation, only one of them gets finalized.
But I'm still skeptical whether `RollingFinality` is the right place to check. Maybe we should just store the hashes in a map, as you said, as soon as they come in via [`verify_block_basic`](https://github.com/poanetwork/parity-ethereum/blob/1c62c33dae03035cf6e80f117c4a71867f739ce1/ethcore/src/engines/authority_round/mod.rs#L1458)?

**Comment by vkomenda** [comment]
> Maybe we should just store the hashes in a map, as you said, as soon as they come in via verify_block_basic

We can. Do you think it would be OK to construct that map at run time from received blocks?

**Comment by vkomenda** [comment]
> Sure, only using finalized blocks is useless, because if there's an equivocation, only one of them gets finalized.

If so, maybe reporting could be done in whatever place in the code does this finalisation.

**Comment by afck** [comment]
> We can. Do you think it would be OK to construct that map at run time from received blocks?

I think so. It should be cheap, since it just stores hashes (and probably validator addresses).

> If so, maybe reporting could be done in whatever place in the code does this finalisation.

Does `RollingFinality` really get to see sibling blocks? I think it's at least sometimes only presented with a given block's linear ancestry in the first place.

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/parity-ethereum/pull/196.
