### ISSUE TITLE
Make the validator set follow the governance contract.

### ISSUE THREAD

**Issue by c0gent** [poanetwork/parity-ethereum#19]
- [x] Retrieve current validator set (validator Ethereum addresses) from Safe Contract.
- [ ] Detect ~completed ballots to add or remove validators~ new staking epochs that change the set of validators.
- [ ] On ~"add"~ new staking epoch, connect to the new nodes and get their `PublicKey`s (unless we can integrate that into the contracts themselves).
- [ ] ~Vote for adding or removing the node in HB.~
- [ ] Perform key generation.
- [ ] Restart Honey Badger.
- [ ] When a node was successfully removed, disconnect from it.

**Comment by afck** [comment]
Also see https://github.com/poanetwork/parity-ethereum/issues/33.

**Comment by afck** [comment]
Closing this in favor of #33.
