### ISSUE TITLE
(Bug) When SYSTEM_ADDRESS makes a call to smart contract, it doesn't fire events

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/parity-ethereum#2]
In Sokol and Core networks, when I query for all events being ran for PoA contract:
```
const POA_ABI = require('./poa.abi');
const Web3 = require('web3');
const sokol = 'https://core.poa.network'
const provider = new Web3.providers.HttpProvider(sokol);
const web3 = new Web3(provider);
const poa = new web3.eth.Contract(POA_ABI, '0x8bf38d4764929064f2d4d3a56520a76ab3df415b');
const fs = require('fs')
poa.getPastEvents({fromBlock: 0}).then((events) => {
  events.forEach((e) => {
    console.log('blockNumber', e.blockNumber ,  'event: ', e.event)
  })
})

```
CORE output:
```
blockNumber 58 event:  MoCInitializedProxyStorage
blockNumber 457 event:  InitiateChange
blockNumber 1366 event:  InitiateChange
blockNumber 2744 event:  InitiateChange
```

SOKOL output:
```
blockNumber 37 event:  MoCInitializedProxyStorage
blockNumber 672 event:  InitiateChange
blockNumber 194806 event:  InitiateChange
blockNumber 200641 event:  InitiateChange
blockNumber 205821 event:  InitiateChange
blockNumber 212436 event:  InitiateChange
blockNumber 267590 event:  InitiateChange
blockNumber 277841 event:  InitiateChange
```

I do have a proof that finalizeChange method was called by SYSTEM_ADDRESS, which does have an event:
https://github.com/poanetwork/poa-network-consensus-contracts/blob/master/contracts/PoaNetworkConsensus.sol#L99

Which was never fired.

**Comment by DemiMarie** [comment]
Is this even an issue now?  We don’t make state-changing calls from `SYSTEM_ADDRESS` anymore, which include firing events.

**Comment by afck** [comment]
See https://github.com/poanetwork/parity-ethereum/issues/1#issuecomment-453817096.
Although I think in principle there's no reason why system calls can't log events. I guess it's kind of an implementation detail of Parity that they don't? (But of course that we can't just change upstream, since the event bloom filter is part of the block, so it's an incompatible change.)
