### ISSUE TITLE
Pay out block rewards using the contract.

### ISSUE THREAD

**Issue by c0gent** [poanetwork/parity-ethereum#20]
- [x] Retrieve block rewards recipients and values from block rewards contract.
- [x] Call `apply_block_rewards()` from Hbbft engine's `on_close_block()` method.
- [ ] Test that rewards are actually applied to validator Ethereum accounts.

**Comment by afck** [comment]
Also see https://github.com/poanetwork/parity-ethereum/issues/31 (basically a duplicate, but has more details).

**Comment by afck** [comment]
Closing in favor of #31.
