### ISSUE TITLE
How does 50%+1 consensus being established in order for SYSTEM_ADDRESS to make a call to finalizeChange

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/parity-ethereum#3]
In PoA, validator set networks, when we propose a new validator set by firing `InitiateChange` event, there is requirement for 50%+1 nodes to agree on the new set and one of the nodes will call `finalizeChange` from SYSTEM_ADDRESS in order to finalize it.
How does it work? 
How does the network know that 50%+1 nodes are online? 
Which channel of communication is being used? 
What happens when 50%+1 are online, but not connected to each other?

**Comment by DemiMarie** [comment]
This isn’t an issue anymore, since we currently do not use the `InitiateChange` event, and we do not make calls from `SYSTEM_ADDRESS` that change state.

**Comment by afck** [comment]
If I understand correctly, this calls are implicit and don't contain any information (what to call, and which parameters to pass) that isn't known by all nodes in advance.
So there is nothing to reach consensus on: A system call is just an additional rule, and not following it is like producing a malformed block or rejecting a valid one.
