### ISSUE TITLE
Feature request for hbbft: reportMalicious

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#32]
Parity should call `ReportingValidatorSet.reportMalicious` function (see https://wiki.parity.io/Validator-Set.html#reporting-contract) when one of the validators behaves badly.

I assume that when `reportMalicious` is called, the `ReportingValidatorSet.InitiateChange` event will be emitted to trigger `Parity` for validator set updating:

```solidity
function reportMalicious(address _validator, uint256 _blockNumber, bytes _proof)
    public
    onlyValidator
{
    // ... check _proof and remove _validator from validator set ...
    emit InitiateChange(blockhash(block.number - 1), newListOfValidators);
    emit MaliciousReported(msg.sender, _validator, _blockNumber);
}
```

**Comment by varasev** [comment]
`ValidatorSet` contract also has the `finalizeChange()` function which is called by Parity when a new validator set is accepted.

Will it be called in our case by hbbft on the block on which a new validator set is applied by the engine?

E.g., let's assume that a node invokes `reportMalicious` function which emits `InitiateChange` event on the block `N`. Then a node calls `finalizeChange()` (according to the description on https://wiki.parity.io/Validator-Set.html) on a block `N+X` where `X` is a delay in blocks. Can we expect such behavior?

**Comment by afck** [comment]
I guess we could call that from Parity whenever the new validator set takes over. Although, depending on how we implement [key generation](https://github.com/poanetwork/parity-ethereum/issues/35#issuecomment-439921675), that information could even be knowable from the contracts alone.

**Comment by varasev** [comment]
One more thought:

Since `newValidatorSet()` takes into account malicious validators reported by `reportMalicious`, I think we should follow the next rule:

If `InitiateChange` event occurs on the same block where `newValidatorSet()` is called, the `newValidatorSet()` should only be called after handling of new validator set retrieved from `InitiateChange` event.

That is necessary to prevent rewriting of correct validator set built by `newValidatorSet()` on the same block.

**Comment by varasev** [comment]
I mean if `InitiateChange` event and `newValidatorSet()` function return different validator sets on the same block, I think there may be collision which one of those sets hbbft will take. It seems to be depended on in which order the corresponding transactions will be included in the block.

Can hbbft engine determine the order of those transactions in the block to get right updated set of validators?

E.g., `InitiateChange` event is emitted before `newValidatorSet()` is called. In this case the validator set returned by `newValidatorSet()` should be used.

In the opposite case, when `newValidatorSet()` is called before `InitiateChange` event is emitted, the validator set returned by `InitiateChange` event should be used.

**Comment by afck** [comment]
Yes, the engine can just always call `newValidatorSet` at the end of the block, after _all_ other transactions, then it will always return the latest list, right?

**Comment by varasev** [comment]
Yes, ok.

**Comment by varasev** [comment]
A note about `reportMalicious` function:

Since this function is called by validator's address, the corresponding transaction is non-system, so the address must have enough balance for gas spending.

If some validator from validator set doesn't have enough balance, he won't be able to call `reportMalicious`.

So, I think we should keep track of validators' balances on every block and require the balance of each address to be more than some threshold.

I propose to check the minimum balance in `BlockReward.reward` function which is called on every block. If validator's balance is lower than the threshold, the validator is fined somehow.

We could also do something similar on the side of hbbft engine. E.g., if some validator doesn't have enough balance, the engine perceives this as not taking part in the consensus.

@igorbarinov  @vbaranov  what do you think?

Another way is to make some function in ReportingValidatorSet contract similar to `reportMalicious` but it would be called by system transaction (which doesn't require gas spending). Since the system transactions don't support events emitting, this function couldn't emit `InitiateChange` event and it would just return a new validator set instead (or an empty array if the set was not changed). E.g.:

```solidity
modifier onlySystem() {
    require(msg.sender == 0xffffFFFfFFffffffffffffffFfFFFfffFFFfFFfE);
    _;
}

function reportMaliciousSystem(address _validator, uint256 _blockNumber, bytes _proof, address _reportingValidator) public onlySystem returns(address[]) {
    bool validatorSetChanged = false;
    // ...
    // ... change `currentValidators` is needed ...
    // validatorSetChanged = true;
    // ...
    if (validatorSetChanged) {
        return currentValidators;
    } else {
        return [];
    }
}
```

instead of the [current `reportMalicious` function](https://github.com/poanetwork/pos-contracts/blob/27b6f8dfe218e3110345c1a42928776e6465644f/contracts/ReportingValidatorSet.sol#L246):

```solidity
function reportMalicious(address _validator, uint256 _blockNumber, bytes _proof) public {
    // ...
    // ... change `currentValidators` is needed ...
    // ...
    emit InitiateChange(blockhash(block.number - 1), currentValidators);
}
```

@afck Could we make that?

**Comment by afck** [comment]
I was thinking a validator who detects a fault would send a regular transaction (containing the `reportMalicious` call), just like any other user would, and probably even send that transaction to the other validators. They all would try to include it (without any special priority) in one of the following batches, just like with any other transaction.

For your second suggestion, we'd do a bit more special handling: We'd include the fault reports in the Honey Badger contribution as a separate field, so all the validators would receive them. Then they would be able to call `reportMaliciousSystem`. That would reduce the delay with which the fault is handled—it would guarantee that misbehavior is punished in the first batch after the one where _f + 1_ witnessed it—, and it wouldn't consume the reporting validator's gas.
(Now that I've typed it out, I guess I'm in favor of the second option.)

**Comment by varasev** [comment]
> I was thinking a validator who detects a fault would send a regular transaction (containing the reportMalicious call), just like any other user would

Yes, this is a regular transaction, I found the corresponding code [here](https://github.com/paritytech/parity-ethereum/blob/1a642fc624bf4b7f6df63253cde5f6dbfee34d60/ethcore/src/engines/validator_set/contract.rs#L111-L125) and [here](https://github.com/paritytech/parity-ethereum/blob/1a642fc624bf4b7f6df63253cde5f6dbfee34d60/ethcore/src/engines/validator_set/contract.rs#L60).

I'm not much familiar with Rust, but the implementation of `transact_contract` looks like it sends non-system transaction: https://github.com/paritytech/parity-ethereum/blob/1a642fc624bf4b7f6df63253cde5f6dbfee34d60/ethcore/src/client/client.rs#L2083-L2098

> For your second suggestion, we'd do a bit more special handling ...

Ok, I agree. I'll replace `reportMalicious` with `reportMaliciousSystem` in `ReportingValidatorSet` contract so it'll look like the [example above](https://github.com/poanetwork/parity-ethereum/issues/32#issuecomment-441981158).

Let's define the parameters of `reportMaliciousSystem` function as follows:
- `address _validator` - the address of malicious validator.
- `uint256 _blockNumber` - the block on which the reported `_validator` misbehaved.
- `bytes _proof` - the bytes sequence which should be the same for all reporting validators in a particular case. The `reportMaliciousSystem` function will compare hash of `_proof` with other reportings to make sure that different validators report the same: https://github.com/poanetwork/pos-contracts/blob/27b6f8dfe218e3110345c1a42928776e6465644f/contracts/ReportingValidatorSet.sol#L256
- `address _reportingValidator` - the address of reporting validator.

**Comment by afck** [comment]
Yes, let's go with the second option then. :+1: 
The other parameters look good, but I'm not sure about `_proof`: Some fault reports won't contain a proof, because not all misbehavior involves a signed message that the other validators could verify as faulty. Also, I don't think it's necessary for all of them to report the _same_ proof. If _f + 1_ nodes detected that a node disconnected, or didn't follow the protocol, that should be enough, even if their observations were about different kinds of faults.

**Comment by varasev** [comment]
Now I think maybe we don't need the `_proof` parameter at all because `reportMaliciousSystem` function will only be called by SYSTEM_ADDRESS (not by validator's address as in case of a regular transaction with `reportMalicious`). So, we could just check that more than 50% of validators reported about the specified malicious validator (`_validator` parameter) discovered on the specified block (`_blockNumber` parameter) without using `_proof`.

**Comment by afck** [comment]
…or even over the course of several blocks? I'd say if someone was reported as malicious by 50% (or even just more than ⅓) of the validators in total, in the last few blocks (hours/days/weeks?), remove them.

**Comment by varasev** [comment]
Could the validators in our case report exact the same block number in the `_blockNumber` param (as in case of `reportMalicious` described [here](https://wiki.parity.io/Validator-Set.html#reporting-contract)) or there are some difficulties with it?

Please take a look at this implementation of `reportMaliciousSystem`: https://github.com/poanetwork/pos-contracts/blob/cb672d00ac837249381388bf5d7f3513cd92a848/contracts/ReportingValidatorSet.sol#L295-L345

This assumes that the new validator set will be returned once in case of more than 50% of validators reported: https://github.com/poanetwork/pos-contracts/blob/cb672d00ac837249381388bf5d7f3513cd92a848/contracts/ReportingValidatorSet.sol#L338

This is how I imagine the reporting at the moment:

E.g., we have validator set consist of 20 validators. If one of the validators is malice, then at least 11 of them must call `reportMaliciousSystem` with the same `_validator` and `_blockNumber` before the new validator set could be applied and returned:

```
1. reportMaliciousSystem(0x123...456, 789, 0x555...321) returns empty array
2. reportMaliciousSystem(0x123...456, 789, 0x555...322) returns empty array
3. reportMaliciousSystem(0x123...456, 789, 0x555...323) returns empty array
4. reportMaliciousSystem(0x123...456, 789, 0x555...324) returns empty array
...
10. reportMaliciousSystem(0x123...456, 789, 0x555...32A) returns empty array
11. reportMaliciousSystem(0x123...456, 789, 0x555...32B) returns new validator set <- here the new validator set is returned because 11 of 20 validators reported
12. reportMaliciousSystem(0x123...456, 789, 0x555...32C) returns empty array
...
19. reportMaliciousSystem(0x123...456, 789, 0x555...333) returns empty array
```

Is it possible?

**Comment by afck** [comment]
If it makes the contract simpler, we could certainly do that, but from the hbbft side, there's no reason why the fault reports would all belong to the same block.

I think it would be more natural to just count them by `_validator`, and if someone was reported _⅓N_ times at all (not in the same block or for the same reason or anything), remove them. Otherwise we either have to have some additional counting mechanism in the Parity code or we allow an attacker to misbehave towards a number of nodes in each epoch without consequences.

**Comment by varasev** [comment]
Ok, I changed the function and renamed it to `reportMaliciousValidator`: https://github.com/poanetwork/pos-contracts/blob/f01478628b7366826c14b4abd9980e0dd1587eda/contracts/ReportingValidatorSet.sol#L242-L293

So now the function has only two parameters:
- `address _validator` - the address of malicious validator.
- `address _reportingValidator` - the address of reporting validator.

If more than ⅓ validators report about `_validator`, the `_validator` will be removed from validator set and banned for 3 months.

After ban period is expired, the address of banned validator can become an observer again and reset `maliceReported[_validator]` array: https://github.com/poanetwork/pos-contracts/blob/f01478628b7366826c14b4abd9980e0dd1587eda/contracts/ReportingValidatorSet.sol#L405

Is it ok that the function returns a non-empty array of new validators only once as I described in [this comment](https://github.com/poanetwork/parity-ethereum/issues/32#issuecomment-442060085)?

**Comment by afck** [comment]
Looks good, just a few suggestions:
* Actually ⅓ of validators should already suffice: `reportCount.mul(3) >= validatorsLength`
* It would be easier if in the Parity code we wouldn't have to keep track who already reported whom. Would it make sense to just silently ignore duplicated reports?
* After each block, every validator will know the full list of reports, and call `reportMailciousValidator` in a loop for each of them. It seems more straightforward to just have a single call per block, that takes a whole list of perpetrator-reporter pairs?

**Comment by varasev** [comment]
> Actually ⅓ of validators should already suffice: reportCount.mul(3) >= validatorsLength

Ok: https://github.com/poanetwork/pos-contracts/commit/ae3c525854a5066e7f51f35a27832bfff7c24960

> It would be easier if in the Parity code we wouldn't have to keep track who already reported whom. Would it make sense to just silently ignore duplicated reports?

You mean we should return an empty array instead of `revert` [here](https://github.com/poanetwork/pos-contracts/blob/ae3c525854a5066e7f51f35a27832bfff7c24960/contracts/ReportingValidatorSet.sol#L270)?

> It seems more straightforward to just have a single call per block, that takes a whole list of perpetrator-reporter pairs?

Do I understand it correctly that you suggest passing `reportMaliciousValidator` the arrays with the same length? E.g.:

```solidity
    function reportMaliciousValidator(address[] _validators, address[] _reportingValidators)
        public
        onlySystem
        returns(address[])
    {
        require(_validators.length == _reportingValidators.length);
        ...
    }
```

**Comment by afck** [comment]
You're right, I guess it doesn't make a difference whether we return an empty array or `revert` there. (It won't even make a difference in the block size, will it?)

> Do I understand it correctly that you suggest passing `reportMaliciousValidator` the arrays with the same length?

Yes, exactly: The validators would first—just via Honey Badger itself—exchange their fault reports. So when they receive the batch, they will all know the same set of fault reports (possibly including different reporters), and can call `reportMaliciousValidators` with it. So I think your first proposal (two arrays with the same length) would be best suited.

**Comment by afck** [comment]
That looks good to me. :+1: 
(I just meant to say that we _will_ occasionally have duplicated reports, and that's fine. Your code does the right thing now: It counts them only as one, ignores the duplicates and moves on to the next report.)

**Comment by varasev** [comment]
Now the `reportMaliciousValidator` for hbbft emits `InitiateChange` event: https://github.com/poanetwork/pos-contracts/commit/9b56c5130097e53b5b26bdc80c72c25079cadbd1

**Comment by DemiMarie** [comment]
This is fixed, I believe.  @varasev can you confirm?
