### ISSUE TITLE
Put contracts in the chain spec, initialize them with first validators.

### ISSUE THREAD

**Issue by afck** [poanetwork/parity-ethereum#46]
The compiled [`pos-contracts`](https://github.com/poanetwork/pos-contracts) should be added to the chain spec, so they are available starting from the genesis block. (Example: [POA sokol spec](https://github.com/poanetwork/parity-ethereum/blob/44710a402b20286e69ea3cc6fcd08f8ff205870b/ethcore/res/ethereum/poasokol.json#L125).)

To configure the initial set of validators, it would be ideal to also read them from the chain spec, and have the engine initialize them. ([`genesis_epoch_data`](https://github.com/paritytech/parity-ethereum/blob/d19bdb642e3c9f4c0bc751a913281f3a45709d56/ethcore/src/engines/mod.rs#L316)?)
In addition, the public master key needs to be specified in the chain spec, and the initial validators need to have their corresponding key shares. These need to be created either by a trusted dealer or in a DKG process that needs to happen outside of the network.

**Comment by DemiMarie** [comment]
This file should be automatically generated during the build process, but doing so would require that the Solidity source code be included as a submodule.  @afck should I try to implement this?

**Comment by afck** [comment]
As discussed, let's keep the repositories separate please.

**Comment by DemiMarie** [comment]
@varasev is it okay if I replace the hard-coded parameters in Solidity with constructor arguments?

**Comment by varasev** [comment]
@DemiMarie Let's replace only the next constants with initializable params:

- RandomAuRa.COLLECT_ROUND_LENGTH (must be divisible by 2)
- ValidatorSetAuRa.STAKING_EPOCH_DURATION
- ValidatorSetAuRa.STAKE_WITHDRAW_DISALLOW_PERIOD (must be less than STAKING_EPOCH_DURATION)

Note that they should be initialized by [`Initializer`](https://github.com/poanetwork/pos-contracts/blob/master/contracts/Initializer.sol) contract (not by the constructor) because the `RandomAuRa` and `ValidatorSetAuRa` contracts are upgradable (so, their implementations can't have constructors).

For this, we need to extend `ValidatorSetAuRa.initialize` function and add similar function for `RandomAuRa`.

**Comment by DemiMarie** [comment]
@varasev what about the addresses?  They should at least be set to values other than `0`.  Should I set them to the values you proposed above?

**Comment by DemiMarie** [comment]
@varasev Also, `addressStorage[OWNER]` ~~is never initialized~~ is initialized in a very non-obvious way, and is accessed throughout the codebase.  Could it be replaced by an internal field?

**Comment by varasev** [comment]
> what about the addresses? They should at least be set to values other than 0. Should I set them to the values you proposed above?

They are already set: https://github.com/poanetwork/pos-contracts/commit/240e6e5e2e695a7761267185bc52adf950fa2951

> Also, addressStorage[OWNER] is initialized in a very non-obvious way, and is accessed throughout the codebase. Could it be replaced by an internal field?

No, it's better to leave it as it is. In upgradable contracts, we use only the state fields defined in [EternalStorage](https://github.com/poanetwork/pos-contracts/blob/master/contracts/eternal-storage/EternalStorage.sol). For upgradability we use [this solution](https://github.com/zeppelinos/labs/tree/master/upgradeability_using_eternal_storage).

**Comment by DemiMarie** [comment]
This is fixed.
