### ISSUE TITLE
Feature request for AuRa: call `reportMalicious` with zero gas price

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#50]
Every validator in AuRa calls [`reportMalicious`](https://github.com/poanetwork/pos-contracts/blob/f7d080fbf5e16bd9b8cdb474bf9541bfe292c796/contracts/ValidatorSetAuRa.sol#L68) function when he sees misbehavior of another validator: https://wiki.parity.io/Validator-Set.html#reporting-contract

We need to make its calling with zero gas price to let the validators report with zero wallet's balance.

The strikethrough text below is no longer relevant.

~~The [`reportMaliciousValidator`](https://github.com/poanetwork/pos-contracts/blob/1240a2e6ab098f18c868324fb2c22454417807d5/contracts/ValidatorSetAuRa.sol#L47) function must be called by SYSTEM_ADDRESS in AuRa instead of standard `reportMalicious` function (described in https://wiki.parity.io/Validator-Set.html).~~

~~The standard `reportMalicious` function looks like this:~~

~~`function reportMalicious(address _validator, uint256 _blockNumber, bytes _proof) public`~~

~~So, what we should do with it:~~

~~- call `reportMaliciousValidator` instead of `reportMalicious` and do that calling from SYSTEM_ADDRESS (instead of validator's address).~~
~~- pass the `_message` and `_signature` parameters instead of `_validator`, `_blockNumber`, `_proof`:~~

~~[`function reportMaliciousValidator(bytes _message, bytes _signature) public onlySystem {...}`](https://github.com/poanetwork/pos-contracts/blob/1240a2e6ab098f18c868324fb2c22454417807d5/contracts/ValidatorSetAuRa.sol#L47)~~

~~The `_message` parameter is a bytes sequence which contains the address of malicious validator (see `_validator` param for the standard `reportMalicious` function) and block number (see `_blockNumber` param for the standard `reportMalicious` function) on which the validator misbehaved. Inside the contract this parameter is parsed as follows: https://github.com/poanetwork/pos-contracts/blob/1240a2e6ab098f18c868324fb2c22454417807d5/contracts/ValidatorSetAuRa.sol#L53-L56~~

~~So, the `_message` param has a length of `52` bytes: `20` bytes for malicious validator address and `32` bytes for block number.~~

~~The `_message` should be signed by validator's private key, and the resulting signature should be passed through the `_signature` param.~~

~~The signature is needed to prevent the possibility of passing arbitrary validator's address and is used to recover validator's address using Solidity's [`ecrecover`](https://solidity.readthedocs.io/en/v0.4.25/units-and-global-variables.html#mathematical-and-cryptographic-functions) function: https://github.com/poanetwork/pos-contracts/blob/1240a2e6ab098f18c868324fb2c22454417807d5/contracts/ValidatorSetAuRa.sol#L138~~

~~I don't know how the signing code could be implemented in Rust, but this should work as web3's `sign` function works: [`web3.eth.accounts.sign`](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#sign). Some examples are available here: https://ethereum.stackexchange.com/questions/1777/workflow-on-signing-a-string-with-private-key-followed-by-signature-verificatio~~

**Comment by varasev** [comment]
The description was updated today :point_up_2:

**Comment by vkomenda** [comment]
I think we should use `ethkey::sign` as the signing function rather than `EngineSigner`'s one to sign the message as it was done here:
https://github.com/poanetwork/parity-ethereum/blob/1323ef7668bac6ba2be0e772d254f721de2fb138/ethcore/src/engines/authority_round/mod.rs#L1255

The `ecrecover` [specification](https://solidity.readthedocs.io/en/v0.5.2/solidity-by-example.html#recovering-the-message-signer-in-solidity) calls for an ECDSA signature with components `r`, `s` and `v`. This is what `ethkey::sign` produces.

**Comment by DemiMarie** [comment]
@vkomenda [`EngineSigner::sign`][1] produces an [`ethkey::Signature`][2] which is also the return type (on success) of [`ethkey::sign`][3].  So we should be fine.


[1]: <https://github.com/poanetwork/parity-ethereum/blob/789bb9c852429594eff3aa194b6333eca01bd30b/ethcore/src/engines/signer.rs#L51>

[2]: <https://github.com/poanetwork/parity-ethereum/blob/789bb9c852429594eff3aa194b6333eca01bd30b/ethkey/src/signature.rs#L30>
[3]: <https://github.com/poanetwork/parity-ethereum/blob/789bb9c852429594eff3aa194b6333eca01bd30b/ethkey/src/signature.rs#L191>

**Comment by vkomenda** [comment]
I see. That's convenient for getting the account private key. I improved typing a bit:
https://github.com/poanetwork/parity-ethereum/blob/2639156636fa626a3f34bde16f4a09f28d064911/ethcore/src/engines/validator_set/mod.rs#L163
We can return the `Error` cleanly. Also there is no need to make the function closure argument mutable.

**Comment by DemiMarie** [comment]
@vkomenda Thank you.

**Comment by afck** [comment]
@vkomenda: Since we're going to use regular service transactions now (see #57), we will go back to calling `reportMalicious`. To make it a service transaction, just set the gas price to zero.

**Comment by DemiMarie** [comment]
Fixed by #59.
