### ISSUE TITLE
Feature request for AuRa: random numbers

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#51]
We have the `Random` contract for AuRa: https://github.com/poanetwork/pos-contracts/blob/master/contracts/RandomAuRa.sol

There're several functions needed to generate random numbers in [`randao`](https://github.com/randao/randao) manner. This is how it should work for AuRa in our case:

I propose to have so-called `collection rounds`. The length of each collection round is 200 blocks. Each collection round is split into two equal phases of 100 blocks: `commits phase` and `reveals phase`.

Each phase is determined by the current block number: https://github.com/poanetwork/pos-contracts/blob/f7d080fbf5e16bd9b8cdb474bf9541bfe292c796/contracts/RandomAuRa.sol#L182-L188

In the `commits phase` validator's node must generate a random number, call [`commitHash`](https://github.com/poanetwork/pos-contracts/blob/f7d080fbf5e16bd9b8cdb474bf9541bfe292c796/contracts/RandomAuRa.sol#L29) function and pass the `keccak256` hash of the number. That must be done by each validator's node `only once` per `commits phase`. E.g., if we have 10 validators, the function will be called only 10 times during the `commits phase`.

The node can call `isCommitPhase()` function to know what's the current phase for the current block: https://github.com/poanetwork/pos-contracts/blob/f7d080fbf5e16bd9b8cdb474bf9541bfe292c796/contracts/RandomAuRa.sol#L182

Then during the `reveals phase` each validator's node must call [`revealSecret`](https://github.com/poanetwork/pos-contracts/blob/f7d080fbf5e16bd9b8cdb474bf9541bfe292c796/contracts/RandomAuRa.sol#L44) function and pass the random number that was generated by the node earlier (during the `commits phase`). The `revealSecret` function must only be called `once` during `reveals phase`.

Once `reveals phase` is completed, the XORed random number [is stored](https://github.com/poanetwork/pos-contracts/blob/f7d080fbf5e16bd9b8cdb474bf9541bfe292c796/contracts/RandomAuRa.sol#L92) by the contract in a public array ([max length of which is 20](https://github.com/poanetwork/pos-contracts/blob/f7d080fbf5e16bd9b8cdb474bf9541bfe292c796/contracts/RandomAuRa.sol#L266-L281)).

Then the next `collection round` begins and so on.

Totally, we will have 20 random numbers refreshed permanently several times a staking epoch (which duration is one week).

If we take 200 blocks as the length of `collection round`, there will be ~600 `collection rounds` per staking epoch which is more than enough to generate 20 random numbers during the staking epoch even if not all validators reveal their numbers sometimes.

To implement the described mechanism we need to make Parity call those functions of `Random` contract **with zero gas price**.

For AuRa the `ReportingValidatorSet` contract will deny making the changes in stakes for the last `6 hours` of staking epoch so that the users couldn't manipulate the outcome in this case. The users will see the random numbers at the last blocks of staking epoch but won't be able to influence the outcome.

**UPDATE** -  the struck out things below ~~will be~~ are implemented in contracts (not in Parity):

~~We should consider it malicious behavior to not reveal (and to not commit), to make sure the last validator can't freely decide whether to reveal or not.~~

~~So, if Parity discovers on the last block of `commits phase` that a validator produced at least one block during the `commits phase` but didn't make a commit, this must be treated as misbehavior. The same is for `reveals phase`: if Parity discovers on the last block of `reveals phase` that a validator produced at least one block during the `reveals phase` but didn't make a reveal, this must be treated as misbehavior.~~

~~An exception: if a validator didn't call `commitHash` or `revealSecret` during the first 400 blocks of new staking epoch, this shouldn't be treated as misbehavior because new validators need to have time to commit/reveal during the full `collection round`.~~

The contracts keep track of intentional nonparticipation in revealing secret numbers as described in the struck out sentences above. To reduce the risk of unintentional node's disconnection, we will recommend the validators to launch more than one node (AuRa supports this) and separate them by different Internet providers (channels).

**Comment by varasev** [comment]
We can't know if the validator wanted to disconnect intentionally or just lost connection, so I think the disconnection shouldn't be treated as misbehavior :thinking:

If he just lost connection and this is reported as misbehavior, the validator will be removed from the set (his stake and his stakers' stakes will be frozen for 3 months), but this seems to be too strict.

**Comment by afck** [comment]
I think making sure you have a stable connection is one of the responsibilities of a validator, and failure to do so _should_ be punished. The question is to what extent, and whether we should have different kinds of penalties.

**Comment by DemiMarie** [comment]
I agree — with a caveat: Validators are individuals, and are generally
non-technical people.   They cannot be expected to maintain a complicated
high-availability setup.  Furthermore, they are likely connecting over
residential internet with no SLA.

Unreliability should be punished far less severely than malicious behavior.

On Dec 12, 2018 9:47 AM, "Andreas Fackler" <notifications@github.com> wrote:

I think making sure you have a stable connection is one of the
responsibilities of a validator, and failure to do so *should* be punished.
The question is to what extent, and whether we should have different kinds
of penalties.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/poanetwork/parity-ethereum/issues/51#issuecomment-446612805>,
or mute the thread

**Comment by varasev** [comment]
The description was updated today :point_up_2:  (the `_signature` param was introduced for the `commitHash` and `revealSecret` functions).

**Comment by varasev** [comment]
The task above was simplified a bit:

![image](https://user-images.githubusercontent.com/33550681/50330336-e1a55a00-050b-11e9-919c-466cbc7a60a8.png)

**Comment by mbr** [comment]
As far as I understand it, we do not need the funds held in escrow like randao does, because the other validators will police potential culprits effectively?

So, breaking the changes down into bits:

* [ ] Introduce a configuration option to the engine parameters, containing the smart contracts address. Setting a `null`-ish value here should disable the randomness feature.
* [ ] Store secrets for various randomness rounds, to be able to recover after a crash. A likely place to put these is _ (to be filled in).
* [ ] Add code that will make calls to `commitHash` and `revealSecret`. The
  precise procedure would be:
  + Call `currentCollectRound()` to get the round number.
  + Load the secret for the specific round from storage, or generate one if
    missing.
  + Call `isRevealPhase()` (and possibly `isCommitPhase()`, for good measure)
    to determine the phase.
  + Call `isCommitted()`/`sentReveal()`; if `true` skip the remaining steps.
  + Call `commitHash()`/`revealSecret()`.

**Comment by varasev** [comment]
> it would be beneficial to encode the fact that "commit equal 0 means no commit made yet" into a similar function `isCommitted(collectRound, validator)`

Ok, `isCommitted` function has been added: https://github.com/poanetwork/pos-contracts/commit/8fd5c082132d448a8c0c70d1baf24728283ef2df

> As far as I understand it, we do not need the funds held in escrow like randao does, because the other validators will police potential culprits effectively?

Right. The contracts will take care of it.

**Comment by DemiMarie** [comment]
@mbr what instructions should we give validators, as far as ensuring that they have continuous service?  The vast majority of individuals cannot afford, and do not have the knowledge to maintain, a true high-availability setup.

Can you give concrete expected availability numbers?

**Comment by DemiMarie** [comment]
@varasev That makes sense, though we will need to see how well that works in practice.

**Comment by mbr** [comment]
@DemiMarie It all depends on the punishment you are dishing out. You could come up with a scheme that allows some temporary "lapses", from something simple like a "three strikes and you're out" to something more sophisticated. I imagine that the implementation would take place in the smart contract though.

**Comment by varasev** [comment]
Since we decided that we can't use system transactions, we'll use [`service transactions`](https://wiki.parity.io/Permissioning.html#gas-price) instead.

So, the functions `commitHash` and `revealSecret` must be called by regular transactions with zero gas price.

The functions' signatures and the description of this issue have been updated accordingly :point_up_2:

**Comment by varasev** [comment]
We could consider this in the future as an enhancement. For now, I think we shouldn't complicate things.

**Comment by DemiMarie** [comment]
This is almost complete, except for `rand_secret` being initialized to `None`.  That is tracked as #67, so I am closing this issue.
