### ISSUE TITLE
Integration tests of PoS contracts against AuRa PoS

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/parity-ethereum#61]
We need integration tests and CI for [PoS contracts](https://github.com/poanetwork/pos-contracts) and [AuRa PoS](https://github.com/poanetwork/parity-ethereum/tree/aura-pos). With a chain spec from #46 we can apply the existing [integration test](https://github.com/varasev/test-block-reward) to PoS contracts.

**Comment by varasev** [comment]
Just for info: we also have a more complex test setup for POA contracts: https://github.com/poanetwork/poa-test-setup

**Comment by vkomenda** [comment]
Here is a preliminary plan for the integration test:
1. get the master branch of the `pos-contracts` repo,
2. compile all PoS contracts,
3. get PoS contract ABIs,
4. get spec.json from the `pos-chain-spec` repo,
5. modify `spec.json` with addresses, bytecode and required arguments of the PoS contracts,
6. start Parity nodes locally,
7. **run tests**,
8. stop Parity nodes.

Since there is already a functioning test `poa-test-setup` written in JS, the language will be JS. If any part of integration would benefit from the test being written in Rust instead, we should plan for that now.

**Comment by varasev** [comment]
@vkomenda I remember you told about two unlocked accounts in `test-block-reward` for the first node: https://github.com/varasev/test-block-reward/blob/b84f740cd9c1fac6dfea67901a888c3c4f6e7a21/config/node1.toml#L32

The first address (which is `0x6546ed725e88fa728a908f9ee9d61f50edc40ad6`) is the account of the first validator: https://github.com/varasev/test-block-reward/blob/b84f740cd9c1fac6dfea67901a888c3c4f6e7a21/config/spec.json#L14

The second address (`0x74e07782e722608448f1cdc3040c874f283340b0`) is just an address of arbitrary account and can be removed from the toml file. It is unlocked for testing purposes - I use this address for making a simple transaction on every block: https://github.com/varasev/test-block-reward/blob/b84f740cd9c1fac6dfea67901a888c3c4f6e7a21/scripts/watch.js#L117

In production mode, there must only be one unlocked address for each node (the address of the corresponding validator).

**Comment by vkomenda** [comment]
@varasev OK, I'll remove the extra unlocked accounts. :+1:

**Comment by DemiMarie** [comment]
I am planning on using Truffle for this, unless you have already begun work @vkomenda.  If you have, could we collaborate?

**Comment by vkomenda** [comment]
@DemiMarie, let's use the same repo https://github.com/poanetwork/pos-test-setup.

**Comment by DemiMarie** [comment]
So we pass a basic smoke test now: the system boots!

**Comment by varasev** [comment]
> So we pass a basic smoke test now: the system boots!

@vkomenda write that he sees the next error:

```
2019-01-18 11:19:45 UTC Local tx 0xd47664894ae0b063dfe9834397b5966e9ba6f6e1d16c6e49584ba2f98ca28d2c below minimal gas price accepted
2019-01-18 11:19:45 UTC Closing the block failed with error Error(Engine(FailedSystemCall("please ensure the contract and method you\'re calling exist! failed to decode empty bytes. if you\'re using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don\'t exist")), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } }). This is likely an error in chain specificiations or on-chain consensus smart contracts.
```

@DemiMarie Do you observe the same error?

**Comment by DemiMarie** [comment]
@varasev I see errors about closing blocks, but not opening them.

**Comment by DemiMarie** [comment]
Currently blocked on #67.

**Comment by DemiMarie** [comment]
#67 is now fixed.  Can we apply the same tests used for [poa-test-setup](/poanetwork/poa-test-setup)?

**Comment by DemiMarie** [comment]
This is fixed.
