### ISSUE TITLE
Initialize `rand_secret` to something other than `None`.

### ISSUE THREAD

**Issue by DemiMarie** [poanetwork/parity-ethereum#67]
This causes opening blocks to fail around block 100.

**Comment by afck** [comment]
I don't think this should be initialized in the `AuthorityRound` constructor: `RandomnessPhase::advance` creates a new secret every time it commits. Something else must be going wrong here.

**Comment by DemiMarie** [comment]
The behavior that I thought was due to this was fixed by #69. Closing.
