### ISSUE TITLE
Keep the InitiateChange event for compatibility with AuRa PoA

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/parity-ethereum#68]
#49 implemented the `getPendingValidators` contract call as a replacement for the corresponding AuRa PoS construct [`InitiateChange`](https://wiki.parity.io/Validator-Set.html). That rendered AuRa incompatible with PoA contracts because the interface underwent a breaking change. We need to restore the interface for AuRa PoA contracts and keep `InitiateChange` somehow.

The question is where to put the switch between `PoA` and `PoS`? Should it go into Parity configuration or in the chain specification?

**Comment by afck** [comment]
The switch is already in the chain specification, and I think that's the right place. I'm not really happy with the name `contractCallGetPendingValidators`, but I also think that option is not really about PoS vs. PoA: It really is just about how the validator set should be read from the contract.

**Comment by DemiMarie** [comment]
This is already fixed.
