### ISSUE TITLE
Don't prepare blocks when not a validator.

### ISSUE THREAD

**Issue by afck** [poanetwork/parity-ethereum#70]
When adding a non-validator node, I see lots of warnings. It looks like ~`on_close_block`~ `Miner::prepare_block` is called anyway! One missing piece that's marked as [`TODO` is extending `Engine::seals_internally`](https://github.com/poanetwork/parity-ethereum/blob/2a7be46cc0389fe25cbbf7c9fb94917355a8e009/ethcore/src/engines/authority_round/mod.rs#L999), so that it returns `Some(false)` if I'm not a validator (or it's not my turn, I guess).
But I'm not even sure whether that will solve the problem.

**Comment by afck** [comment]
Unassigning for now. This is just a warning and doesn't break the network, so I'll work on the contract changes first.

**Comment by varasev** [comment]
Also, those warnings are supposed to appear when [`engine_signer` is defined in config](https://github.com/poanetwork/posdao-test-setup/blob/a128806ca901848ad0400430ea8738aee2026335/config/node1.toml#L34), aren't they?

**Comment by afck** [comment]
Yes, it still behaves the same way with https://github.com/poanetwork/posdao-contracts/commit/50b4c19420e6ece27d3da9bc463119f8c4ab25fe. The contracts aren't at fault here.

> Also, those warnings are supposed to appear when [`engine_signer` is defined in config](https://github.com/poanetwork/posdao-test-setup/blob/a128806ca901848ad0400430ea8738aee2026335/config/node1.toml#L34), aren't they?

That's when they appear currently, yes, because `seals_internally` just always returns `Some(true)` if a signer is defined. The TODO is about checking in addition whether it's actually our turn to create a block, so that we don't waste CPU time on creating lots of blocks that in the end we refuse to seal.

Note that it's not even warnings, just trace and debug messages:

```
2019-02-07 09:59:25  IO Worker #0 TRACE miner  update_sealing
2019-02-07 09:59:25  IO Worker #0 TRACE miner  requires_reseal: sealing enabled
2019-02-07 09:59:25  IO Worker #0 TRACE miner  requires_reseal: should_disable_sealing=false; forced=true, has_local=false, internal=Some(true), had_requests=false
2019-02-07 09:59:25  IO Worker #0 TRACE miner  update_sealing: preparing a block
2019-02-07 09:59:25  IO Worker #0 TRACE miner  prepare_block: No existing work - making new block
2019-02-07 09:59:25  IO Worker #0 TRACE engine  Multi ValidatorSet retrieved for block 0.
2019-02-07 09:59:25  IO Worker #0 TRACE engine  New block issued #30 ― calling emitInitiateChange()
2019-02-07 09:59:25  IO Worker #0 DEBUG miner  Attempting to push 1 transactions.
2019-02-07 09:59:25  IO Worker #0 DEBUG miner  Adding tx 0xcecfbd59e20fafc4a8ab4a36d7fc23f81b1899ce0e218db071d5aff0cb99b3c3 took 16 ms
2019-02-07 09:59:25  IO Worker #0 DEBUG miner  Pushed 1 transactions in 16 ms
2019-02-07 09:59:25  IO Worker #0 TRACE reward  Block reward benefactors: [(0xbbcaa8d48289bb1ffcf9808d9aa4b1d215054c78, Author)]
2019-02-07 09:59:25  IO Worker #0 TRACE miner  update_sealing: engine indicates internal sealing
2019-02-07 09:59:25  IO Worker #0 TRACE miner  seal_block_internally: attempting internal seal.
2019-02-07 09:59:25  IO Worker #0 DEBUG engine  Zooming to epoch for block 0xf88f…8154
2019-02-07 09:59:25  IO Worker #0 TRACE engine  Fetched proposer for step 309905993: 0x522d…89b2
2019-02-07 09:59:25  IO Worker #0 TRACE engine  generate_seal: 0xbbca…4c78 not a proposer for step 309905993.
```

But they show that the miner determines ([via both `seals_internally` and `forced_sealing()` in this case](https://github.com/poanetwork/parity-ethereum/blob/4cfa67cf6f4597c30bbbc7b6ba51fbf93d282a1d/ethcore/src/miner/miner.rs#L605)) that it can seal. It then [creates a new block](https://github.com/poanetwork/parity-ethereum/blob/4cfa67cf6f4597c30bbbc7b6ba51fbf93d282a1d/ethcore/src/miner/miner.rs#L393), adds [our contract calls](https://github.com/poanetwork/parity-ethereum/blob/4cfa67cf6f4597c30bbbc7b6ba51fbf93d282a1d/ethcore/src/engines/validator_set/safe_contract.rs#L304) and [user transactions](https://github.com/poanetwork/parity-ethereum/blob/4cfa67cf6f4597c30bbbc7b6ba51fbf93d282a1d/ethcore/src/miner/miner.rs#L542) to it, and only then, in [`AuthorityRound::generate_seal`](https://github.com/poanetwork/parity-ethereum/blob/4cfa67cf6f4597c30bbbc7b6ba51fbf93d282a1d/ethcore/src/miner/miner.rs#L651) realizes [it can't actually seal the block](https://github.com/poanetwork/parity-ethereum/blob/4cfa67cf6f4597c30bbbc7b6ba51fbf93d282a1d/ethcore/src/engines/authority_round/mod.rs#L1132).
Pushing transactions onto blocks involves executing them; I think that's quite wasteful in terms of CPU.

**Comment by varasev** [comment]
Ok, we could deal with this, I guess?

**Comment by afck** [comment]
Yes, it shouldn't break anything. It would still be nice to fix it, to avoid a lot of spam in the logs and wasted CPU time.

**Comment by DemiMarie** [comment]
Problem: can `Call` be fooled by malicious validators?  If so, I don’t see any way to avoid a memory leak of cached reports.

**Comment by afck** [comment]
That's a good point; maybe we should just set some fixed limit for the size of the cache. (Did you mean to post in #97 instead?)

**Comment by afck** [comment]
The ideal fix for this would:
* Never start preparing a block with a number where we know it isn't our turn.
* Always start preparing a block a short while before it is our turn, so that when our turn arrives, we just finished preparing.

In particular we need to find out when exactly [`Miner::prepare_block`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L364) and [`Engine::seals_internally`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/engines/authority_round/mod.rs#L999) are called.

`Miner::prepare_block` is private. It's called in [`Miner::prepare_pending_block`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L762) (also private) if there's no block in the sealing queue, and in [`MinerService::update_sealing`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L1091) if [`Miner::requires_reseal`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L578) is `true` on the best block number. `Miner::prepare_pending_block` is called in [`Miner::prepare_and_update_sealing`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L809) if `Engine::seals_internally` is `Some(true)`, and in [`MinerService::work_package`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L1145) if `Engine::seals_internally` is `None`. `Miner::prepare_and_update_sealing` is called in [`MinerService::import_external_transactions`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L875) and [`MinerService::import_own_transactions`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L898). Let's find out where those four `MinerService` methods are called:
* `MinerService::update_sealing` is called in ([one of the above](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L809) and) [`MinerService::chain_new_blocks`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L1189) if new external blocks were imported. Apart from that, it is only called in [`Client`'s impl of `EngineClient::update_sealing`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/client/client.rs#L2392), which in turn is called in [`<AuthorityRound as Engine>::step`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/engines/authority_round/mod.rs#L934) and [`<TransitionHandler as IoHandler<()>>::timeout`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/engines/authority_round/mod.rs#L901).
* `MinerService::work_package` is called from the `rpc` crate and [`<StratumJobDispatcher as JobDispatcher>::job`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/stratum.rs#L121).
* `MinerService::import_external_transactions`' call sites are [`<Client as IoClient>::queue_transactions`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/client/client.rs#L2138) and [`<Miner as MinerService>::import_claimed_local_transaction`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/miner/miner.rs#L924), which is also called from `rpc`.
* `MinerService::import_own_transactions` is called in lots of places.

I'm confused but it looks like preparing a new block is considered whenever new transactions or blocks are imported as well as periodically on a timeout.

Since in our case [`seals_internally`](https://github.com/poanetwork/parity-ethereum/blob/fe70b4ab0362161fa5951960f063111a9db744a7/ethcore/src/engines/mod.rs#L297) will never return `None` (we don't require external input) it seems reasonable to just return `Some(true)` if the latest block known to the client indicates that it's our turn to seal the next one. (Assuming that preparing a block is quick enough to easily do it within our turn—that might be a problem for large block sizes or fast block rates!) But it certainly would be better to start slightly sooner than that.

**Comment by phahulin** [comment]
Just to put it here: it looks like new transactions, indeed, can cause a reseal of the block, depending on configuration:
```
     --reseal-on-txs=[SET]
        Specify which transactions should force the node to
        reseal a block. SET is one of: none - never reseal on
        new transactions; own - reseal only on a new local
        transaction; ext - reseal only on a new external
        transaction; all - reseal on all new transactions.
        (default: own)
```

**Comment by vkomenda** [comment]
Possibly this option is not taking a proper effect because `reseal_on_txs` has already been set to `none` in the configuration for each node and other validator's blocks still get prepared.
