### ISSUE TITLE
Make sure contract calls apply to the current open block.

### ISSUE THREAD

**Issue by afck** [poanetwork/parity-ethereum#75]
We are currently adding the randomness contract calls (#51) [to the transaction queue](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/engines/authority_round/util.rs#L99) in [`AuthorityRound::on_new_block`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/engines/authority_round/mod.rs#L1141) and assume they will be applied to the current open block. We make the _constant_ calls [via the `EngineClient`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/engines/authority_round/util.rs#L73) using [`BlockId::Latest`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/engines/authority_round/mod.rs#L1159) and assume that will always give us up-to-date information.

We should either verify that our assumptions are correct, or make those calls in a more direct way to the currently open block.

It would be easy to pass an `OpenBlock` to `on_new_block` instead of an `ExecutedBlock`: It is available as `r` at the only call site, [`OpenBlock::new`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/block.rs#L288). `OpenBlock` has a [`push_transaction` method](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/block.rs#L330) that would allow us to add transactions directly, without the queue.

[`Client::call_contract`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/client/client.rs#L1405), which is currently used for the constant calls, first turns the call into a transaction in [`Client::contract_call_tx`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/client/client.rs#L1232) and then passes it to [`Client::call`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/client/client.rs#L1469), which in turn uses [`Client::do_virtual_call`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/client/client.rs#L1244) (a static method) to retrieve the result of the transaction. Note that this updates the state, but that state object is just a local copy that [has been created in `call_contract`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/client/client.rs#L1407).
`Client::do_virtual_call` uses [`Executive::transact_virtual`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/executive.rs#L790), which automatically adds sufficient gas to the state and executes the transaction. (The method name seems to be misleading: it is _meant_ to be used with cloned state objects that won't be persisted anywhere, but what the method does is no more virtual than [`Executive::transact`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/executive.rs#L781).)
We should probably do something like [`Client::contract_call_tx`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/client/client.rs#L1232) in [`BoundContract`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/engines/authority_round/util.rs#L18), and then just use [`Client::call`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/client/client.rs#L1232) with a clone of the current block's state.

**Comment by afck** [comment]
Alternatively, instead of changing what's passed into `on_new_block`, we could also just copy the relevant part of the `push_transaction` implementation, so we keep our changes local.

**Comment by afck** [comment]
Another complication is that we need the client to turn the call data into a transaction first. It looks like we'll need to change the `Client` trait for that: We need something like [`Client::transact`](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/client/client.rs#L2113), but instead of putting the transaction on the queue, it should return it to us.

**Comment by DemiMarie** [comment]
@afck I checked, and it seems that `on_new_block` _does not get called._

**Comment by afck** [comment]
No, these methods would all be just for use-cases like ours, where the current block author has to make contract calls.

**Comment by DemiMarie** [comment]
@afck what would happen if any other node tried to do this?

**Comment by afck** [comment]
You can only call the methods with a mutable `ExecutedBlock` (that contains a `State` and everything), and they are applied to that block. If it doesn't end up getting sealed and accepted into the blockchain, then the transaction is effectively not executed, and the constant calls are made to a "fork".

**Comment by afck** [comment]
I have an [implementation](https://github.com/poanetwork/parity-ethereum/tree/afck-calls) that seems to work now: I realized that `on_new_block` is also called in other nodes, not only in the block author. I had missed that because its [only call site](https://github.com/poanetwork/parity-ethereum/blob/fea0f23508fd3c271e87201e2f77eef52fc314d0/ethcore/src/block.rs#L287) is in [`OpenBlock::new`](https://github.com/poanetwork/parity-ethereum/blob/fea0f23508fd3c271e87201e2f77eef52fc314d0/ethcore/src/block.rs#L255). But that, of course, gets called in lots of places, in particular in [`block::enact`](https://github.com/poanetwork/parity-ethereum/blob/fea0f23508fd3c271e87201e2f77eef52fc314d0/ethcore/src/block.rs#L553) and therefore in [`block::enact_verified`](https://github.com/poanetwork/parity-ethereum/blob/fea0f23508fd3c271e87201e2f77eef52fc314d0/ethcore/src/block.rs#L599), which seem to replay a block's transactions. This is used in [`Importer::check_and_lock_block`](https://github.com/poanetwork/parity-ethereum/blob/fea0f23508fd3c271e87201e2f77eef52fc314d0/ethcore/src/client/client.rs#L358), which in the end compares the resulting state to the one in the block header (that's the place where it used to fail for me when `on_new_block` would always insert more transactions), which in turn is called by [`Importer::import_verified_blocks`](https://github.com/poanetwork/parity-ethereum/blob/fea0f23508fd3c271e87201e2f77eef52fc314d0/ethcore/src/client/client.rs#L264), which has several call sites.
A similar story applies to `on_close_block`, I think.

So we can't assume that we're creating a block in either of those calls. I'm not entirely sure what we _can_ assume: E.g. if someone sent us any bogus block, could they trick us into creating a transaction that reveals our secret?

Maybe it's cleanest to add yet another method to `Engine`, that is only called from the `Miner`, but not from `OpenBlock` itself. It would allow the _author_ to insert transactions, but nobody else.

**Comment by DemiMarie** [comment]
@afck I will handle this.

**Comment by DemiMarie** [comment]
[`Miner::prepare_block`](https://github.com/poanetwork/parity-ethereum/blob/fea0f23508fd3c271e87201e2f77eef52fc314d0/ethcore/src/miner/miner.rs#L364-L545) calls [`PrepareOpenBlock::prepare_open_block`](https://github.com/poanetwork/parity-ethereum/blob/fea0f23508fd3c271e87201e2f77eef52fc314d0/ethcore/src/client/traits.rs#L411-L419) whenever it needs to autthor a new block.  Other than code that is only compiled for testing, the only implementation of that trait is [Client::prepare_open_block](https://github.com/poanetwork/parity-ethereum/blob/fea0f23508fd3c271e87201e2f77eef52fc314d0/ethcore/src/client/client.rs#L2263-L2301).  I plan to have that method call `block_author_transactions`.

**Comment by afck** [comment]
Caveat: `prepare_block` is called even if we're not the proposer ([2-year-old TODO](https://github.com/poanetwork/parity-ethereum/blob/9c705910597b3dc31855d74c44e8b72fa9ce6cb9/ethcore/src/engines/authority_round/mod.rs#L998)).
That's wasteful but at least if we don't put our transactions in the queue, it won't do any harm (other than wasting CPU).

**Comment by DemiMarie** [comment]
Marking as low-priority, per discussion on Zoom.  The current approach is more robust, and fixing this should be left until after the network is operational.

**Comment by varasev** [comment]
@afck Could we close this?
