### ISSUE TITLE
Error when starting a node: "Block import failed"

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#83]
Sometimes the third node doesn't want to start with [`pos-test-setup`](https://github.com/poanetwork/pos-test-setup) on my machine. This happens not always: sometimes it works, sometimes it doesn't.

I'm attaching the log files for the three nodes.

[node1.txt](https://github.com/poanetwork/parity-ethereum/files/2818224/node1.txt)
[node2.txt](https://github.com/poanetwork/parity-ethereum/files/2818225/node2.txt)
[node3.txt](https://github.com/poanetwork/parity-ethereum/files/2818226/node3.txt)

However, [this commit](https://github.com/poanetwork/parity-ethereum/commit/7e9a265441b4810115e2b0050bb7da0373072d4a) solved the issue but it is not merged into `aura-pos` branch.

**Comment by DemiMarie** [comment]
I think I found the problem: under certain circumstances, `on_new_block` tries to insert a transaction that isn’t valid anymore.  Perhaps the blockchain has progressed too far?

If that is the problem, then it makes sense that 7e9a265441b4810115e2b0050bb7da0373072d4a would fix it.  Should I merge that to `aura-pos`?

**Comment by DemiMarie** [comment]
@varasev

**Comment by varasev** [comment]
If there is nothing harmful in that commit, then yes, we could merge it.

**Comment by DemiMarie** [comment]
Fixed by 7e9a265441b4810115e2b0050bb7da0373072d4a

**Comment by afck** [comment]
> a transaction that isn’t valid anymore

In what sense was it invalid? `on_new_block` only put the transaction into the queue, it didn't execute it, so how could it fail?
