### ISSUE TITLE
Improvement suggestion: use `BlockReward.reward` instead of `commitHash` and `revealSecret`

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#84]
I wonder if it's possible to pass the params `_secretHash`, `_cipher`, and `_secret` to `BlockReward.reward` function as extra parameters and don't use `RandomAuRa.commitHash` and `RandomAuRa.revealSecret` by validator?

This would allow us to save gas in a block and make Random a bit more reliable.

It's just a proposal. If it's not possible, we are OK with the current solution.

**Comment by DemiMarie** [comment]
@varasev I am not sure.  Probably.

**Comment by varasev** [comment]
Got it. OK, let's use the current solution with regular service transactions then.
