### ISSUE TITLE
Fix the validator set unit tests.

### ISSUE THREAD

**Issue by afck** [poanetwork/parity-ethereum#93]
As of https://github.com/poanetwork/parity-ethereum/commit/d745959a6c04a099623f27e46cbfb98556fc4854, the ethcore unit tests fail:
```
---- engines::validator_set::contract::tests::reports_validators stdout ----
thread 'engines::validator_set::contract::tests::reports_validators' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', ethcore/src/engines/validator_set/contract.rs:201:3

---- snapshot::tests::proof_of_authority::fixed_to_contract_only stdout ----
thread 'snapshot::tests::proof_of_authority::fixed_to_contract_only' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', ethcore/src/snapshot/tests/proof_of_authority.rs:115:4

---- snapshot::tests::proof_of_authority::fixed_to_contract_to_contract stdout ----
thread 'snapshot::tests::proof_of_authority::fixed_to_contract_to_contract' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', ethcore/src/snapshot/tests/proof_of_authority.rs:115:4
```
That's probably because the tests [load](https://github.com/poanetwork/parity-ethereum/blob/0ab7410968655683dac3784a9c87c4ccab49a0d4/ethcore/src/spec/spec.rs#L980) the spec file [`validator_contract.json`](https://github.com/poanetwork/parity-ethereum/blob/aura-pos/ethcore/res/validator_contract.json), which doesn't have e.g. the `emitInitiateChange` function: our changes are backward incompatible.
We could either update that spec file or make our changes backward compatible: Create a separate `ValidatorSet` implementation for our purpose, and revert our changes to the existing ones.

**Comment by afck** [comment]
My first attempt to replace the spec doesn't work (still the same failures): https://github.com/poanetwork/parity-ethereum/commit/f13e6cff07e80cb3f64553a7e0284029deabbb17

**Comment by afck** [comment]
* [ ] The reason why my [modified `reports_validators`](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR167) still doesn't work is that the [posdao-contracts](https://github.com/poanetwork/posdao-contracts) currently ignore benign reports and don't provide a getter to even check whether a validator has been reported.
The [`disliked` call](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR206) would need to be replaced by a call to such a getter. The [last assertion](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR222) is (I think) to check whether validator 1 has been removed after being reported. That seems more like a test for the actual contract rather than the validator set Rust code and could maybe just be removed?
* [ ] Our engine now requires the account to be unlocked, so [this](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR170) and [this](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f09a40f65abe52c0c2ea1121a90b2ffcR76) is probably needed.
* [ ] The tests in `ethcore/src/snapshot/tests/proof_of_authority.rs` need a chain spec with a "multi" validator set that switches between different contracts. It would probably be best to port [the test contract](https://gist.github.com/anonymous/2a43783647e0f0dfcc359bd6fd81d6d9) to the new API.

**Comment by DemiMarie** [comment]
> The [`disliked` call](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR206) would need to be replaced by a call to such a getter. The [last assertion](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR222) is (I think) to check whether validator 1 has been removed after being reported. That seems more like a test for the actual contract rather than the validator set Rust code and could maybe just be removed?

I believe that the last assertion tests that the Rust code refuses a block from a removed validator.

**Comment by DemiMarie** [comment]
Can we use our own `spec.json`?  We already have one.

**Comment by DemiMarie** [comment]
@afck can we make these three separate issues?

> * [ ]  The reason why my [modified `reports_validators`](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR167) still doesn't work is that the [posdao-contracts](https://github.com/poanetwork/posdao-contracts) currently ignore benign reports and don't provide a getter to even check whether a validator has been reported.

We can just drop the test instead.  It does nothing for us.

>   The [`disliked` call](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR206) would need to be replaced by a call to such a getter. The [last assertion](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR222) is (I think) to check whether validator 1 has been removed after being reported. That seems more like a test for the actual contract rather than the validator set Rust code and could maybe just be removed?

IMO, this tests that the engine rejects blocks from removed validators.  As such, it needs to be done with a `spec.json` that includes the actual production contract code.

> * [ ]  Our engine now requires the account to be unlocked, so [this](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f370346cf997740c5728eea7b94c984eR170) and [this](https://github.com/poanetwork/parity-ethereum/commit/06ce8e63e314429bb5b86001ff948e85e3512e92#diff-f09a40f65abe52c0c2ea1121a90b2ffcR76) is probably needed.

Agreed.  I can make a PR for that.

> * [ ]  The tests in `ethcore/src/snapshot/tests/proof_of_authority.rs` need a chain spec with a "multi" validator set that switches between different contracts. It would probably be best to port [the test contract](https://gist.github.com/anonymous/2a43783647e0f0dfcc359bd6fd81d6d9) to the new API.

Perhaps.

I seriously think we should consider just dropping those tests, though, at least when PoS is in use.  They test PoA, which we don’t use.

In any case, our Rust code is far more tightly coupled with the on-chain consensus contracts than PoA is.  I think we should use either our production Solidity code, or purpose-built mock contracts.

**Comment by afck** [comment]
>  I think we should use either our production Solidity code, or purpose-built mock contracts.

Yes, I think for _unit_ tests, it would make sense to have the latter. But you're right: If they are too tightly coupled, we should just stick to our production contracts, even for the tests. (Not sure whether they are.)

In either case, I don't think `reports_validators` is obsolete: We still have (or are currently implementing) reporting, and ideally it should be tested.

>  As such, it needs to be done with a spec.json that includes the actual production contract code.

Yes, that's what I started with in [`afck-tests`](https://github.com/poanetwork/parity-ethereum/tree/afck-tests), but there were a lot of details (e.g. initial account balances) that needed to be adapted for the test.

**Comment by vkomenda** [comment]
> I haven't found out yet which function [this line](https://github.com/poanetwork/parity-ethereum/blob/b784d17d26145ec9c1088d1899bf6d23ae252d1a/ethcore/src/engines/validator_set/contract.rs#L206) is calling.

I guess this line is supposed to call `reportBenign` with the account `7d577a597b2742b498cb5cf0c26cdcd726d39e6e` as the argument because of [this](https://github.com/poanetwork/parity-ethereum/blob/b784d17d26145ec9c1088d1899bf6d23ae252d1a/ethcore/src/spec/spec.rs#L977) and [this](https://github.com/poanetwork/parity-ethereum/blob/b58a3ed0ad746b6e7d92e119f75058cdf895c897/ethcore/res/contracts/test_validator_set.json#L6).
There aren't many other functions with one argument anyway. The code `d8f2e0bf` features in the constructors of `ethcore/res/validator_(safe_)contract.json`.

**Comment by vkomenda** [comment]
Currently the problem lies in [obscure bytecode](https://github.com/poanetwork/parity-ethereum/blob/cd7c1192fe5ea90fd8e955b77ac20c924949f388/ethcore/res/validator_contract.json#L40) in the test validator set contract. It should be updated to our latest modification of AuRa. When updating, the initial validator accounts (those with initial balance) should be referred to from within the contract bytecode, as they are now. There is a [tutorial](https://medium.com/@ayushyachitransh/parity-validator-set-da4df44b97d9) available for producing bytecode from other test contracts which I tried to use.

**Comment by afck** [comment]
I can make the snapshot tests go a few steps further by updating the contracts in [the spec](https://github.com/poanetwork/parity-ethereum/blob/aura-pos/ethcore/src/snapshot/tests/test_validator_contract.json), too, and adding a `setValidators` method, but it still fails to import block 4. I'm out of ideas for now. :pensive:

**Comment by afck** [comment]
I think I found the reason: I get `InvalidNonce` errors, so the problem is probably that we push some transaction (randomness? initiate change?) onto the block and use up the report's nonce. #107 should solve this.

**Comment by varasev** [comment]
Done in #129.
