### ISSUE TITLE
Pass transaction `data` field to `TxPermission.allowedTxTypes()` function

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#95]
I have an idea to pass transaction `data` field to [`TxPermission.allowedTxTypes()`](https://github.com/poanetwork/posdao-contracts/blob/a034012d6b9bfe34610416a7f799185302b91cb8/contracts/TxPermission.sol#L89) function.

This would allow us to filter zero gas price transactions not only by `to` and `gasPrice` fields but also by function signature which is passed in `data` field when `to` is a contract's address.

This way we could prevent malicious validator from calling the functions of `ValidatorSetAuRa` and `RandomAuRa` contracts which shouldn't be called at the moment. This would help to prevent spending block gas when some malicious validator tries to perform a lot of fail transactions. So, this could prevent the possibility of DDoS organized by some validator.

**Comment by vkomenda** [comment]
This is a great idea. Making analysis happen sooner would help DDoSing less likely. What `data` field are you thinking about? Sounds rather abstract. The [caller](https://github.com/poanetwork/parity-ethereum/blob/4cfa67cf6f4597c30bbbc7b6ba51fbf93d282a1d/ethcore/src/tx_filter.rs#L67) doesn't have any. We might have to pass that as an argument from somewhere else.

**Comment by afck** [comment]
I think it would just mean passing the transaction's [`data` field](https://github.com/poanetwork/parity-ethereum/blob/4cfa67cf6f4597c30bbbc7b6ba51fbf93d282a1d/ethcore/transaction/src/transaction.rs#L114) into the [permission contract call](https://github.com/poanetwork/parity-ethereum/blob/4cfa67cf6f4597c30bbbc7b6ba51fbf93d282a1d/ethcore/src/tx_filter.rs#L112).
